import type { RectangleLayer } from "../domain/rectangleLayerSchema";
import type { ShapeText } from "../domain/shapeTextSchema";
import type { TextLayer } from "../domain/textLayerSchema";

export type EditableLayerPatch = Partial<{
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  opacity: number;
  opacityEnabled: boolean;
  text: string;
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  fontStyle: TextLayer["fontStyle"];
  lineHeight: number;
  letterSpacing: number;
  textAlign: TextLayer["textAlign"];
  verticalAlign: TextLayer["verticalAlign"];
  autoResize: TextLayer["autoResize"];
  textCase: TextLayer["textCase"];
  kerningPairs: boolean;
  ligatures: boolean;
  fill: string;
  fillEnabled: boolean;
  stroke: string | null;
  strokeWidth: number;
  cornerEnabled: boolean;
  cornerRadius: number;
  cornerRadii: RectangleLayer["cornerRadii"];
  donut: number;
  sweep: number;
  startAngle: number;
  arrowHeadSize: number;
  arrowStartStyle: "none" | "triangle" | "line" | "diamond" | "circle";
  arrowEndStyle: "none" | "triangle" | "line" | "diamond" | "circle";
  src: string | null;
  fit: "fill" | "contain";
  placeholderColor: string;
  shapeText: ShapeText;
}>;
